<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="chassis_mass" value="0.8" /> <!-- arbitrary value for base mass -->
  <xacro:property name="chassis_width" value="0.3" />
  <xacro:property name="chassis_length" value="0.35" />
  <xacro:property name="chassis_height" value="0.32" />
  <xacro:property name="chassis_base_offset" value="0.07" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.040" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_pos_front" value="0.10" />
  <xacro:property name="wheel_pos_rear" value="0.10" />
  <xacro:property name="wheel_pivot_pos_front" value="0.12" />
  <xacro:property name="z_offset" value="-${chassis_height/2}" /> <!-- Space btw top of beam and the each joint -->

  <!-- Base Link -->
  <link name="${prefix}base_link">
  </link>

  <!-- BASE_FOOTPRINT LINK -->
  <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base_footprint"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}base_footprint">
  </link>


  <!-- Chassis Link -->
  <joint name="${prefix}chassis_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}chassis"/>
    <origin xyz="-${chassis_length/2} 0 ${chassis_base_offset}"/>
  </joint>

  <link name="${prefix}chassis">
    <visual>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="white"/>
    </visual>
    <collision>
          <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <gazebo reference="chassis">
      <material>Gazebo/Green</material>
  </gazebo>


  Steering Left Pivot Link
  <joint name="${prefix}steering_left_pivot_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}steering_left_pivot"/>
    <origin xyz="${wheel_pos_front} ${wheel_pivot_pos_front} 0.02" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="${prefix}steering_left_pivot">
    <visual>
        <geometry>
            <cylinder length="0.1" radius="0.025"/>
        </geometry>
        <material name="white"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="0.1" radius="0.025"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="0.1" radius="0.025">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="steering_left_pivot">
      <material>Gazebo/White</material>
  </gazebo>


  <!-- left wheel front Link -->
  <joint name="${prefix}left_wheel_joint" type="continuous">
    <parent link="${prefix}steering_left_pivot"/>
    <child link="${prefix}left_wheel"/>
    <origin xyz="0 0.045 -0.02" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="${prefix}left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_wheel">
      <material>Gazebo/Black</material>
  </gazebo>



  <!-- Steering Right Pivot Link -->
  <joint name="${prefix}steering_right_pivot_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}steering_right_pivot"/>
    <origin xyz="${wheel_pos_front} ${-wheel_pivot_pos_front} 0.02" rpy="0 0 ${PI}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="${prefix}steering_right_pivot">
    <visual>
        <geometry>
            <cylinder length="0.1" radius="0.025"/>
        </geometry>
        <material name="white"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="0.1" radius="0.025"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="0.1" radius="0.025">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="steering_right_pivot">
      <material>Gazebo/White</material>
  </gazebo>


  <!-- right wheel front Link -->
  <joint name="${prefix}right_wheel_joint" type="continuous">
    <parent link="${prefix}steering_right_pivot"/>
    <child link="${prefix}right_wheel"/>
    <origin xyz="0 0.045 -0.02" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="${prefix}right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="right_wheel">
      <material>Gazebo/Black</material>
  </gazebo>


  <!-- left wheel rear Link -->
  <joint name="${prefix}left_wheel_rear_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}left_wheel_rear"/>
    <origin xyz="-${wheel_pos_rear} ${chassis_width/2 + wheel_len/2} 0" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="${prefix}left_wheel_rear">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_wheel_rear">
      <material>Gazebo/Black</material>
  </gazebo>


  <!-- right wheel rear Link -->
  <joint name="${prefix}right_wheel_rear_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}right_wheel_rear"/>
    <origin xyz="-${wheel_pos_rear} -${chassis_width/2 + wheel_len/2} 0" rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="${prefix}right_wheel_rear">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="right_wheel_rear">
      <material>Gazebo/Black</material>
  </gazebo>

  </xacro:macro>

</robot>