<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="chassis_mass" value="0.8" /> <!-- arbitrary value for base mass -->
  <xacro:property name="chassis_width" value="0.22" />
  <xacro:property name="chassis_length" value="0.28" />
  <xacro:property name="chassis_height" value="0.22" />
  <xacro:property name="chassis_base_offset" value="0.12" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.040" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_pos_front" value="0.10" />
  <xacro:property name="wheel_pos_rear" value="0.10" />
  <xacro:property name="wheel_pivot_pos_front" value="0.12" />
  <xacro:property name="z_offset" value="-${chassis_height/2}" /> <!-- Space btw top of beam and the each joint -->

  <!-- Base Link -->
  <link name="base_link">
  </link>

  <!-- BASE_FOOTPRINT LINK -->
  <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint">
  </link>


  <!-- Chassis Link -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="${-chassis_length/2} 0 ${chassis_base_offset}"/>
  </joint>

  <link name="chassis">
    <visual>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="green"/>
    </visual>
    <collision>
          <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <gazebo reference="chassis">
      <material>Gazebo/Green</material>
  </gazebo>


  <!-- left wheel front Link -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="left_wheel"/>
    <origin xyz="${chassis_length} ${chassis_width/2} -0.07" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_wheel">
      <material>Gazebo/Black</material>
  </gazebo>



  <!-- right wheel front Link -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="right_wheel"/>
    <origin xyz="${chassis_length} ${-chassis_width/2} -0.07" rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="right_wheel">
      <material>Gazebo/Black</material>
  </gazebo>


  <!-- rear caster Link -->
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="${wheel_radius} 0 -0.07" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="caster_wheel">
      <material>Gazebo/Black</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
  </gazebo>

  </xacro:macro>

</robot>